# A dictionary of routes that can be updated from a database or a JSON file

routes_data = {
    "Ikeja-CMS": [
        "Ikeja",
        "Opebi",
        "Shoprite",
        "Secretariat",
        "Onward",
        "Seven Up",
        "Ogudu Oke",
        "CMS",
    ],
    "Mile2-Agbara": [
        "Mile2",
        "Festac",
        "Agboju",
        "Iyana-Iba",
        "LASU",
        "Okokomaiko",
        "Iyanasashi",
        "Federal",
        "Vespa",
        "Agbara",
    ],
    "Ikeja-Yaba": [
        "Ikeja",
        "Opebi",
        "Shoprite",
        "Secretariat",
        "Onward",
        "Seven Up",
        "Ojota",
        "Maryland",
        "Anthony",
        "Obanikoro",
        "Palmgoove",
        "Onipanu",
        "Yaba",
    ],
}